name: Publish library to NPM
run-name: Publish library to NPM by ${{ github.actor }}

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-to-npm:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
            
      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Typecheck
        run: bun typecheck

      - name: Run Biome
        run: bun biome ci
      
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        id: changesets
        with:
          publish: bun changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        